/**
 * 统一错误码。
 * 所有抛出给用户的错误必须使用这里的 code，不要临时拼字符串。
 */
export const ERROR_CODES = {
  // 通用
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // 认证
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",

  // 内容类型
  CONTENT_TYPE_NOT_FOUND: "CONTENT_TYPE_NOT_FOUND",
  CONTENT_TYPE_UID_DUPLICATE: "CONTENT_TYPE_UID_DUPLICATE",
  CONTENT_TYPE_HAS_ENTRIES: "CONTENT_TYPE_HAS_ENTRIES",
  CONTENT_TYPE_FIELD_INVALID: "CONTENT_TYPE_FIELD_INVALID",

  // 内容
  ENTRY_NOT_FOUND: "ENTRY_NOT_FOUND",
  ENTRY_SLUG_DUPLICATE: "ENTRY_SLUG_DUPLICATE",

  // 媒体
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
  ASSET_UPLOAD_FAILED: "ASSET_UPLOAD_FAILED",

  // 插件
  PLUGIN_NOT_FOUND: "PLUGIN_NOT_FOUND",
  PLUGIN_CONFIG_INVALID: "PLUGIN_CONFIG_INVALID",

  // Webhook
  WEBHOOK_NOT_FOUND: "WEBHOOK_NOT_FOUND",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
export type ErrorLiteralCode = (typeof ERROR_CODES)[ErrorCode];

/** HTTP 状态码到错误码的映射参考。 */
export const HTTP_STATUS: Record<number, number> = {
  400: 400,
  401: 401,
  403: 403,
  404: 404,
  409: 409,
  500: 500,
};

/** 由错误码推导推荐的 HTTP 状态码。接受任意字符串以兼容动态错误码。 */
export function httpStatusForCode(code: string): number {
  switch (code) {
    case ERROR_CODES.VALIDATION_ERROR:
    case ERROR_CODES.CONTENT_TYPE_FIELD_INVALID:
    case ERROR_CODES.PLUGIN_CONFIG_INVALID:
      return 400;
    case ERROR_CODES.UNAUTHORIZED:
    case ERROR_CODES.INVALID_CREDENTIALS:
    case ERROR_CODES.TOKEN_EXPIRED:
    case ERROR_CODES.TOKEN_INVALID:
    case ERROR_CODES.REFRESH_TOKEN_INVALID:
      return 401;
    case ERROR_CODES.FORBIDDEN:
      return 403;
    case ERROR_CODES.NOT_FOUND:
    case ERROR_CODES.CONTENT_TYPE_NOT_FOUND:
    case ERROR_CODES.ENTRY_NOT_FOUND:
    case ERROR_CODES.ASSET_NOT_FOUND:
    case ERROR_CODES.PLUGIN_NOT_FOUND:
    case ERROR_CODES.WEBHOOK_NOT_FOUND:
      return 404;
    case ERROR_CODES.CONFLICT:
    case ERROR_CODES.CONTENT_TYPE_UID_DUPLICATE:
    case ERROR_CODES.CONTENT_TYPE_HAS_ENTRIES:
    case ERROR_CODES.ENTRY_SLUG_DUPLICATE:
      return 409;
    default:
      return 500;
  }
}
